cBioPortal/cancerhotspots

LICENSE
updated license to GNU AFFERO GENERAL PUBLIC LICENSE
=> updated license to GNU AGPL

web/src/main/java/org/cmo/cancerhotspots/CancerHotspots.java, web/src/main/java/org/cmo/cancerhotspots/domain/HotspotMutation.java, web/src/main/java/org/cmo/cancerhotspots/domain/MapConversion.java, web/src/main/java/org/cmo/cancerhotspots/service/HotspotMutationService.java, web/src/main/java/org/cmo/cancerhotspots/service/internal/SignificantHotspotMutationService.java, web/src/main/java/org/cmo/cancerhotspots/web/HotspotController.java, web/src/main/resources/static/index.html, web/src/main/resources/static/src/css/hotspots.css, web/src/main/resources/static/src/js/component/StackedBar.js, web/src/main/resources/static/src/js/data/HotspotDataProxy.js, web/src/main/resources/static/src/js/main.js, web/src/main/resources/static/src/js/view/CompositionView.js, web/src/main/resources/static/src/js/view/HotspotTableView.js
This adds default copyright and license information for individual source files.
=> added copyright and license information for each individual source file

web/src/main/resources/static/src/css/hotspots.css
replaced background with background-color
=> minor css update

web/src/main/resources/static/src/js/component/StackedBar.js
This fixes a bug in the array sort function
=> fixed array sorting function in StackedBar class

web/src/main/resources/static/index.html, web/src/main/resources/static/src/css/hotspots.css
This removes the big **About** title, and adds the full citation text.
=> simplified about section

web/src/main/resources/static/index.html, web/src/main/resources/static/src/js/view/HotspotTableView.js
- initially ordering the table by ascending q-value
- fixed the PubMed image reference
=> minor fixes

web/src/main/resources/static/index.html
=> updated CMO link

web/src/main/resources/static/index.html
=> added Google Analytics support

web/pom.xml, web/src/main/java/org/cmo/cancerhotspots/CancerHotspots.java, web/src/main/java/org/cmo/cancerhotspots/domain/HotspotMutation.java, web/src/main/java/org/cmo/cancerhotspots/web/AdminController.java, web/src/main/java/org/cmo/cancerhotspots/web/HotspotController.java, web/src/main/resources/static/src/js/data/HotspotDataProxy.js, web/src/main/resources/static/src/js/data/VariantDataProxy.js
added swagger support for the API documentation
=> swagger support

pom.xml, web/pom.xml, web/src/main/resources/static/index.html, web/src/main/resources/static/src/css/hotspots.css, web/src/main/resources/static/src/css/oncokb.css
This PR fixes the issue #31
- added msk icon to top right corner
- added funding information below the contributor list
- updated about content
- various style improvements
- upgraded spring boot version
=> minor content and style update

web/src/main/resources/static/index.html, web/src/main/resources/static/src/js/view/HotspotTableView.js
=> updated scale function for the variant amino acid tooltip bar

webapp/src/main/resources/static/index.html, webapp/src/main/resources/static/src/css/hotspots.css, webapp/src/main/resources/static/src/js/controller/CancerHotspots.js
Added a separate download page, accessible via the main menu.
=> Added a separate download page

service/src/main/java/org/cmo/cancerhotspots/service/HotspotMutationService.java, service/src/main/java/org/cmo/cancerhotspots/service/internal/ClusteredHotspotMutationService.java, service/src/main/java/org/cmo/cancerhotspots/service/internal/SingleResidueHotspotMutationService.java, webapp/src/main/java/org/cmo/cancerhotspots/controller/HotspotController.java, webapp/src/main/resources/static/src/js/controller/CancerHotspots.js, webapp/src/main/resources/static/src/js/data/ClusterDataProxy.js, webapp/src/main/resources/static/src/js/data/HotspotDataProxy.js, webapp/src/main/resources/static/src/js/data/VariantDataProxy.js, webapp/src/main/resources/static/src/js/util/ProxyUtils.js
- Lists are now body parameter for POST requests
- Added some new endpoints
- Updated client code accordingly
=> Cleanup and improvements for the Hotspots API

webapp/src/main/resources/static/src/js/data/VariantDataProxy.js
Fixed a bug that was causing incorrect variant query results (for the inner variant tool tip).
=> Variant query bug fix

webapp/pom.xml
Make the jar name same with repo name.
=> Update jar name

.travis.yml
Add Travis CI and auto push image to docker hub on new tagged release both for normal & 3d.
=> Add travis & docker auto push image

.travis.yml
Old version did not push to docker hub:
https://travis-ci.org/cBioPortal/cancerhotspots#L1242
Hopefully this works
=> Push to docker hub w/o --email

model/src/main/java/org/cmo/cancerhotspots/model/Cluster.java, model/src/main/java/org/cmo/cancerhotspots/model/HotspotMutation.java, model/src/main/java/org/cmo/cancerhotspots/model/TumorTypeComposition.java, persistence/src/main/java/org/cmo/cancerhotspots/persistence/internal/ClusterRepositoryImpl.java, service/src/main/java/org/cmo/cancerhotspots/service/internal/HotspotDataImportService.java
This PR is intended to fix the invalid Map types created by the swagger client generator.
=> Updated model to serialize Map as Object

webapp/src/main/resources/static/index.html, webapp/src/main/resources/static/src/js/controller/CancerHotspots.js
both for `Cancer Hotspots` and `3D Hotspots`
=> updated publication links

webapp/src/main/resources/static/src/js/controller/CancerHotspots.js
=> Updated v2 MAF file link

webapp/src/main/java/org/cmo/cancerhotspots/controller/ProxyController.java, webapp/src/main/resources/static/src/js/view/ResidueView.js
=> Added proxy to make http servlets work within https

webapp/src/main/resources/static/src/js/view/ResidueView.js
=> Using https pdb service
